import React, { useEffect, useState } from 'react';
import { FileText, Loader2, UsersRound } from 'lucide-react';
import { getAcademicReports, getAcademicStudents } from '../../api/endpoints';
import type { AcademicReport, AcademicStudent } from '../../api/endpoints';

export const AcademicReportsPage: React.FC = () => {
  const [reports, setReports] = useState<AcademicReport[]>([]);
  const [students, setStudents] = useState<AcademicStudent[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([getAcademicReports(), getAcademicStudents()]).then(([reportResponse, studentResponse]) => { setReports(reportResponse.data); setStudents(studentResponse.data); }).finally(() => setLoading(false)); }, []);
  const studentName = (id: string) => students.find((student) => student.id === id)?.name || id;
  if (loading) return <div className="flex items-center justify-center py-20"><Loader2 size={28} className="animate-spin text-indigo-500" /></div>;
  return <div className="page-shell mx-auto max-w-6xl space-y-6"><div className="page-header"><div><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100 text-emerald-600"><FileText size={20} /></span><div><h1 className="page-title">Evaluation sheets</h1><p className="page-description">Published student reports ready to share.</p></div></div></div><span className="inline-flex items-center gap-2 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><UsersRound size={14} /> {reports.length} published</span></div>{reports.length === 0 ? <div className="ui-card p-8 text-center text-sm text-slate-500">No reports have been published yet.</div> : <div className="grid gap-5 lg:grid-cols-2">{reports.map((report) => <article key={report.id} className="ui-card space-y-4 p-5"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold text-slate-800">{studentName(report.studentId)}</h2><p className="mt-1 text-xs text-slate-500">Published {new Date(report.publishedAt).toLocaleString()}</p></div><span className="rounded-md bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">Published</span></div><p className="text-sm leading-relaxed text-slate-600">{report.summary}</p><div className="space-y-2">{report.scores.map((score) => <div key={score.key} className="flex items-center justify-between text-xs"><span className="text-slate-500">{score.label}</span><strong className="text-slate-700">{score.score}/{score.maxScore}</strong></div>)}</div><div className="grid gap-3 border-t border-slate-100 pt-3 sm:grid-cols-2"><div><h3 className="text-[10px] font-bold uppercase tracking-wider text-emerald-600">Strengths</h3><p className="mt-1 text-xs text-slate-500">{report.strengths.join(' · ') || '—'}</p></div><div><h3 className="text-[10px] font-bold uppercase tracking-wider text-amber-600">Next steps</h3><p className="mt-1 text-xs text-slate-500">{report.improvements.join(' · ') || '—'}</p></div></div></article>)}</div>}</div>;
};
